### ISSUE TITLE
Looking for new owner

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/bash#6]

**Comment by haydenbleasel** [comment]
@MTco  
@finseth  
@enociz  
@Kirkhammetz  
@BenjaminNelan  
@mattu08  
@gld1982ltd  
@datagutt  
@grosskur  
@unserializable  
@anthonyjfio  
@Pe46dro  
@laarc  
@SantoshSrinivas79  
@glnster  
@michaelrhodes  
@Ne02ptzero  
@aliou  
@czajkovsky  
@cttwapps  
@dimaahawk

**Comment by BenjaminNelan** [comment]
Guessing it's a matter of time, but any reason for wanting a new owner? Noticed you've posted similar threads on a number of your other projects too.

**Comment by haydenbleasel** [comment]
@BenjaminNelan Just too busy nowadays to manage open-source, but I don't want to let down all the people using these projects by either deleting them or just not maintaining them. I'm sure there's someone better than me to own these projects :)

**Comment by finseth** [comment]
I'm up for maintaining this project @haydenbleasel :)

**Comment by haydenbleasel** [comment]
@finseth Too easy! Check your email.

**Comment by finseth** [comment]
Cool, I just updated my profile with a public email address 👌

**Comment by finseth** [comment]
Thank you @haydenbleasel - I'll take good care of her :)

**Comment by haydenbleasel** [comment]
Haha thanks mate :)
